server:
  port: 10085
  servlet:
   contextPath: /demo
spring:
  application:
    name: framework


framework:
  app:
    home: D:/Projects/RunData/webim_home


security:
  login:
    cas:
      enabled: false
      localHome:
      casHome:
    dao:
      enabled: true
    success:
      write-log: true
      regist-token: false
      target-url: /
    failure:
      write-log: false
      target-url: /system/mainframe/login/error
    captcha:
      check-time: 0
      check-type: 0
    retry:
      check-type: H
      max-try-times: 0
      lock-minites: 10
      check-time-interval: 3
  logout:
    target-url: /system/mainframe/login
  access:
    enable-anonymous: false
    resource-must-audited: false
  http:
    csrf-enable: false
    filter-continue-authentication: false
    x-frame-options-mode: deny
